FROM quay.io/toolbx-images/archlinux-toolbox:latest
ARG REPO

COPY pacman.conf /etc/pacman.conf
RUN pacman-key --init
RUN pacman -Sy --noconfirm archlinux-keyring
RUN pacman -Syu --needed --noconfirm zsh bat python && pacman -Scc --noconfirm
